databases:
  - name: postgres
    ipAllowList: []
    databaseName: Budget_App
    user: postgres

services:
  - type: web
    name: Budget_App
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
